#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KinveyLogin.Resource", IsApplication=true)]

namespace KinveyLogin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::KinveyXamarinAndroid.Resource.Attribute.circleCrop = global::KinveyLogin.Resource.Attribute.circleCrop;
			global::KinveyXamarinAndroid.Resource.Attribute.imageAspectRatio = global::KinveyLogin.Resource.Attribute.imageAspectRatio;
			global::KinveyXamarinAndroid.Resource.Attribute.imageAspectRatioAdjust = global::KinveyLogin.Resource.Attribute.imageAspectRatioAdjust;
			global::KinveyXamarinAndroid.Resource.Color.common_action_bar_splitter = global::KinveyLogin.Resource.Color.common_action_bar_splitter;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_default = global::KinveyLogin.Resource.Color.common_signin_btn_dark_text_default;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_disabled = global::KinveyLogin.Resource.Color.common_signin_btn_dark_text_disabled;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_focused = global::KinveyLogin.Resource.Color.common_signin_btn_dark_text_focused;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_dark_text_pressed = global::KinveyLogin.Resource.Color.common_signin_btn_dark_text_pressed;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_default_background = global::KinveyLogin.Resource.Color.common_signin_btn_default_background;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_default = global::KinveyLogin.Resource.Color.common_signin_btn_light_text_default;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_disabled = global::KinveyLogin.Resource.Color.common_signin_btn_light_text_disabled;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_focused = global::KinveyLogin.Resource.Color.common_signin_btn_light_text_focused;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_light_text_pressed = global::KinveyLogin.Resource.Color.common_signin_btn_light_text_pressed;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_text_dark = global::KinveyLogin.Resource.Color.common_signin_btn_text_dark;
			global::KinveyXamarinAndroid.Resource.Color.common_signin_btn_text_light = global::KinveyLogin.Resource.Color.common_signin_btn_text_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_full_open_on_phone = global::KinveyLogin.Resource.Drawable.common_full_open_on_phone;
			global::KinveyXamarinAndroid.Resource.Drawable.common_ic_googleplayservices = global::KinveyLogin.Resource.Drawable.common_ic_googleplayservices;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_disabled_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_focus_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_disabled_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_disabled_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_disabled_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_focus_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_focus_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_normal_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_normal_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_normal_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_normal_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_pressed_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_pressed_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_icon_pressed_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_icon_pressed_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_disabled_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_focus_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_disabled_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_focus_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_disabled_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_disabled_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_disabled_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_focus_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_focus_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_focus_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_focus_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_normal_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_normal_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_normal_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_normal_light;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_pressed_dark = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_pressed_dark;
			global::KinveyXamarinAndroid.Resource.Drawable.common_signin_btn_text_pressed_light = global::KinveyLogin.Resource.Drawable.common_signin_btn_text_pressed_light;
			global::KinveyXamarinAndroid.Resource.Id.adjust_height = global::KinveyLogin.Resource.Id.adjust_height;
			global::KinveyXamarinAndroid.Resource.Id.adjust_width = global::KinveyLogin.Resource.Id.adjust_width;
			global::KinveyXamarinAndroid.Resource.Id.none = global::KinveyLogin.Resource.Id.none;
			global::KinveyXamarinAndroid.Resource.Integer.google_play_services_version = global::KinveyLogin.Resource.Integer.google_play_services_version;
			global::KinveyXamarinAndroid.Resource.String.auth_google_play_services_client_facebook_display_name = global::KinveyLogin.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::KinveyXamarinAndroid.Resource.String.auth_google_play_services_client_google_display_name = global::KinveyLogin.Resource.String.auth_google_play_services_client_google_display_name;
			global::KinveyXamarinAndroid.Resource.String.common_android_wear_notification_needs_update_text = global::KinveyLogin.Resource.String.common_android_wear_notification_needs_update_text;
			global::KinveyXamarinAndroid.Resource.String.common_android_wear_update_text = global::KinveyLogin.Resource.String.common_android_wear_update_text;
			global::KinveyXamarinAndroid.Resource.String.common_android_wear_update_title = global::KinveyLogin.Resource.String.common_android_wear_update_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_api_unavailable_text = global::KinveyLogin.Resource.String.common_google_play_services_api_unavailable_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_enable_button = global::KinveyLogin.Resource.String.common_google_play_services_enable_button;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_enable_text = global::KinveyLogin.Resource.String.common_google_play_services_enable_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_enable_title = global::KinveyLogin.Resource.String.common_google_play_services_enable_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_error_notification_requested_by_msg = global::KinveyLogin.Resource.String.common_google_play_services_error_notification_requested_by_msg;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_button = global::KinveyLogin.Resource.String.common_google_play_services_install_button;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_text_phone = global::KinveyLogin.Resource.String.common_google_play_services_install_text_phone;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_text_tablet = global::KinveyLogin.Resource.String.common_google_play_services_install_text_tablet;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_install_title = global::KinveyLogin.Resource.String.common_google_play_services_install_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_invalid_account_text = global::KinveyLogin.Resource.String.common_google_play_services_invalid_account_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_invalid_account_title = global::KinveyLogin.Resource.String.common_google_play_services_invalid_account_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_needs_enabling_title = global::KinveyLogin.Resource.String.common_google_play_services_needs_enabling_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_network_error_text = global::KinveyLogin.Resource.String.common_google_play_services_network_error_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_network_error_title = global::KinveyLogin.Resource.String.common_google_play_services_network_error_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_notification_needs_update_title = global::KinveyLogin.Resource.String.common_google_play_services_notification_needs_update_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_notification_ticker = global::KinveyLogin.Resource.String.common_google_play_services_notification_ticker;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_sign_in_failed_text = global::KinveyLogin.Resource.String.common_google_play_services_sign_in_failed_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_sign_in_failed_title = global::KinveyLogin.Resource.String.common_google_play_services_sign_in_failed_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_unknown_issue = global::KinveyLogin.Resource.String.common_google_play_services_unknown_issue;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_unsupported_text = global::KinveyLogin.Resource.String.common_google_play_services_unsupported_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_unsupported_title = global::KinveyLogin.Resource.String.common_google_play_services_unsupported_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_update_button = global::KinveyLogin.Resource.String.common_google_play_services_update_button;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_update_text = global::KinveyLogin.Resource.String.common_google_play_services_update_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_update_title = global::KinveyLogin.Resource.String.common_google_play_services_update_title;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_updating_text = global::KinveyLogin.Resource.String.common_google_play_services_updating_text;
			global::KinveyXamarinAndroid.Resource.String.common_google_play_services_updating_title = global::KinveyLogin.Resource.String.common_google_play_services_updating_title;
			global::KinveyXamarinAndroid.Resource.String.common_open_on_phone = global::KinveyLogin.Resource.String.common_open_on_phone;
			global::KinveyXamarinAndroid.Resource.String.common_signin_button_text = global::KinveyLogin.Resource.String.common_signin_button_text;
			global::KinveyXamarinAndroid.Resource.String.common_signin_button_text_long = global::KinveyLogin.Resource.String.common_signin_button_text_long;
			global::KinveyXamarinAndroid.Resource.String.library_name = global::KinveyLogin.Resource.String.library_name;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView = global::KinveyLogin.Resource.Styleable.LoadingImageView;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView_circleCrop = global::KinveyLogin.Resource.Styleable.LoadingImageView_circleCrop;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::KinveyLogin.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::KinveyXamarinAndroid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::KinveyLogin.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::ModernHttpClient.Resource.String.library_name = global::KinveyLogin.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::KinveyLogin.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::KinveyLogin.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int common_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_signin_btn_text_light = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int adjust_height = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int adjust_width = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int btnLinkToLoginScreen = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int btnLinkToRegister = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btnLogin = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int btnRegister = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int password = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int txtPassword = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int txtUserName = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int username = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001d
			public const int common_google_play_services_api_unavailable_text = 2130968605;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_sign_in_failed_text = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int common_google_play_services_sign_in_failed_title = 2130968606;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001c
			public const int common_open_on_phone = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int common_signin_button_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int common_signin_button_text_long = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int library_name = 2130968612;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
