#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Feedr.Resource", IsApplication=true)]

namespace Feedr
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int avatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Upload = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Upload2 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int BtnUploadPostImage = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int PostDate = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int PostDescription = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int PostProfilePic = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int PostUsrName = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int btnLinkToLoginScreen = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int btnLinkToRegister = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int btnLogin = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int btnPost = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int btnProfilePic = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int btnRegister = 2131034135;
			
			// aapt resource value: 0x7f05000c
			public const int feedImage1 = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int list = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int name = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int password = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int profilePic = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int textView1 = 2131034133;
			
			// aapt resource value: 0x7f050009
			public const int timestamp = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int txtEmail = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int txtPassword = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int txtStatusMsg = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int txtUrl = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int txtUserName = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int username = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddPost = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Feed_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Register = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
