#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleMusicPlayer.Resource", IsApplication=true)]

namespace SimpleMusicPlayer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int adele = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_backward = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_forward = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_next = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_play = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_playlist = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_previous = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_repeat = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_repeat_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_shuffle = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_shuffle_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gradient_bg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int gradient_bg_hover = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_launcher = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int img_btn_backward = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int img_btn_backward_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int img_btn_forward = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int img_btn_forward_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int img_btn_next = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int img_btn_next_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int img_btn_pause = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int img_btn_pause_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int img_btn_play = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int img_btn_play_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int img_btn_playlist = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int img_btn_playlist_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int img_btn_previous = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int img_btn_previous_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int img_btn_repeat = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int img_btn_repeat_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int img_btn_shuffle = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int img_btn_shuffle_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int img_seekbar_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int img_seekbar_progress_blue = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int list_selector = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int seek_handler = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int seekbar_progress = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int seekbar_progress_bg = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int track_info_bg = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnBackward = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int btnForward = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnNext = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int btnPlay = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int btnPlaylist = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int btnPrevious = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int btnRepeat = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int btnShuffle = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int player_footer_bg = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int player_header_bg = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int songCurrentDurationLabel = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int songProgressBar = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int songThumbnail = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int songTitle = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int songTotalDurationLabel = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int timerDisplay = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bg_player_footer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bg_player_header = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int player = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int playlist = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int playlist_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int rounded_corner = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
