#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RecyclerViewTutorial.Resource", IsApplication=true)]

namespace RecyclerViewTutorial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int flip = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_left_to_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_right_to_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int cardview_compat_inset_shadow = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_elevation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_default_radius = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_forward = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_read = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int lollipop = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int lollipop_android5 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int add = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int card_view = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int cbxStart = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int imageButton1 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int imageButton2 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int imageButton3 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imgView = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int recyclerView = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int txtMessage = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int txtName = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int txtSubject = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int txtTime = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int row2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int actionbar = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CardView_Dark = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CustomActionBarTheme = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MyActionBar = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
