//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
    }
}
